// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MisteryApp.Repository.Contexts;

#nullable disable

namespace MisteryApp.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MisteryApp.Repository.Ingest.Entities.IngestRejectedFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("RejectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("IngestRejectedFiles", (string)null);
                });

            modelBuilder.Entity("MisteryApp.Repository.Ingest.Entities.IngestRunEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InputPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ProcessedFiles")
                        .HasColumnType("int");

                    b.Property<int>("RejectedFiles")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("int");

                    b.HasKey("RunId");

                    b.ToTable("IngestRuns", (string)null);
                });

            modelBuilder.Entity("MisteryApp.Repository.Ingest.Entities.IngestRejectedFileEntity", b =>
                {
                    b.HasOne("MisteryApp.Repository.Ingest.Entities.IngestRunEntity", "IngestRun")
                        .WithMany("RejectedFileEntities")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestRun");
                });

            modelBuilder.Entity("MisteryApp.Repository.Ingest.Entities.IngestRunEntity", b =>
                {
                    b.Navigation("RejectedFileEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
